steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'common-deploy'
      - '--attribute=apps=all'
options:
  logging: CLOUD_LOGGING_ONLY
